kind: pipeline
type: default
name: blogFrontend


steps:
  - name: deployment
    image: quay.io/honestbee/drone-kubernetes
    settings:
      kubernetes_server: https://172.17.16.12:6443            # k8s 集群地址
      kubernetes_token: k8sToken
      namespace: blog-project
      deployment: deployment
      repo: docker.carrotwu.com/blog/blog-web
      container: blog-web                          # 容器名                  # 需要被部署的镜像 TAG
trigger:
  branch:
  - master
