language: node_js
node_js:
  - "10.16.0"
services:
  - docker

before_install:
  - yarn install

script:
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t carrotwu/ts-learning:latest .
  - docker push carrotwu/ts-learning:latest

