---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  namespace: NAMESPACE
  labels:
    k8s-app: APP_NAME
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 3
  selector:
    matchLabels:
      k8s-app: APP_NAME
  template:
    metadata:
      labels:
        k8s-app: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: docker.carrotwu.com/blog/IMAGE_NAME
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: APP_NAME
  name: APP_NAME
  namespace: NAMESPACE
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    k8s-app: APP_NAME
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: APP_NAME-nodeport
  name: APP_NAME-nodeport
  namespace: NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 30001
      targetPort: 8888
  selector:
    k8s-app: APP_NAME
